version: "3.8"
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"

  app1:
    build: .
    container_name: app1
    depends_on:
      - broker
      - fluentd
    environment:
      CLIENT_URL: http://app2:8088
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: docker.app1
  app2:
    build: .
    container_name: app2
    depends_on:
      - broker
      - fluentd
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
    ports:
      - "8088:8080"
    logging:
        driver: "fluentd"
        options:
            fluentd-address: 127.0.0.1:24224
            tag: docker.app2

  fluentd:
    build:
     context: .
     dockerfile_inline: |
       FROM fluent/fluentd:v1.19-debian-2
       USER root
       RUN fluent-gem install fluent-plugin-elasticsearch
       USER fluent
    container_name: fluentd
    user: "0"
    environment:
      - FLUENTD_UID=0
    volumes:
      - ./config/fluent.conf:/fluentd/etc/fluent.conf
      - ./data:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:9.4.2
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ELASTIC_PASSWORD: 'elastic'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'

  kibana:
    image: kibana:9.4.2
    container_name: kibana
    environment:
        ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
        ELASTICSEARCH_SERVICEACCOUNTTOKEN: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpqV1V2RTJteFJzS053RzZwTU84NDd3"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local