spring:
  application:
    name: distributed-logging
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: logging-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest


kafka:
  topicos:
    async: message.async

simple:
  service:
    base-url: ${CLIENT_URL:http://localhost:8080}

kind: Application

