flowchart TD
    C[inicializador MDC]
    A[Client Http] --> C
    B[Client Kafka] --> C
    C --> D{Tem correlationId\n nos headers?}
    D -->|Sim| E[Registrar MDC\ncom correlationId]
    D -->|Não| F[Gerar correlationId\npara MDC]
    E --> G
    F --> G
    G[Executar lógica de negócio] --> H[Registrar logs\ncom MDC]
